# Generated by Django 4.0.3 on 2022-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kompania',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ishlab chiqaruvchi nomi '),
        ),
        migrations.AlterField(
            model_name='product',
            name='mudat',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Yaroqlilik mudati'),
        ),
    ]
