# Generated by Django 4.0.3 on 2022-03-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_customer_body_customer_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='barecode',
            new_name='barcode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='body',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='title',
        ),
    ]
