# Generated by Django 4.0.3 on 2022-03-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_barecode_product_barcode_remove_customer_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
