# Generated by Django 4.0.3 on 2022-03-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kg',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Mahsulot og'irligi(gr)"),
        ),
    ]
