# Generated by Django 4.0.3 on 2022-03-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('smartfon', 'Smartfon'), ('telefon', 'Telefon'), ('computer', 'Copmuter'), ('planshet', 'Planshet'), ('noutbook', 'Noutbook'), ('smartwatch', 'SmartWatch')], max_length=150, verbose_name='Mahsulot turi')),
                ('nom', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('rang', models.CharField(blank=True, choices=[('qora', 'Qora'), ('oq', 'Oq'), ('qizil', 'Qizil'), ('sariq', 'Sariq'), ('kulrang', 'Kulrang'), ('moviy', 'Moviy'), ('yashil', 'Yashil'), ('jigarang', 'Jigarang'), ('pushti', 'Pushti'), ('boshqa', 'Boshqa')], max_length=50, null=True, verbose_name='Mahsulot rangi')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='repo_mahsulotlar/%Y/%m/%d/', verbose_name='Mahsulot rasmi')),
                ('son', models.IntegerField(blank=True, default=0, null=True, verbose_name='Mahsulot soni')),
                ('kompania', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ishlab chiqaruvchi nomi ')),
                ('mudat', models.CharField(blank=True, max_length=150, null=True, verbose_name='Yaroqlilik mudati')),
                ('kg', models.IntegerField(blank=True, default=0, null=True, verbose_name="Mahsulot og'irligi(gr)")),
                ('izoh', models.CharField(blank=True, max_length=300, null=True, verbose_name="Qo'shimcha izoh")),
                ('sana', models.DateField(auto_now=True, verbose_name='Hisobot vaqti')),
                ('yangilanish', models.DateTimeField(auto_now=True, verbose_name="O'zgartirish kiritilgan sana")),
            ],
        ),
    ]
