# Generated by Django 4.0.3 on 2022-03-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_son_alter_report_son'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tekshir',
            field=models.CharField(choices=[('ha', 'Ha'), ('yoq', "Yo'q")], default='yoq', max_length=100, verbose_name="Ha/Yo'q"),
        ),
    ]
