# Generated by Django 4.0.3 on 2022-03-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_pic/%Y/%m/%d/', verbose_name='Admin rasmi'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
